use_frameworks!

target 'ResearchSuiteAppFramework_Example' do
  pod 'ResearchSuiteAppFramework/Core', :path => '../'
  pod 'ResearchSuiteAppFramework/OldCore', :path => '../'
  pod 'ResearchSuiteAppFramework/Lab', :path => '../'

  pod "sdlrkx"
  pod "OhmageOMHSDK"
  pod "OhmageOMHSDK/RSTBSupport"
  pod "OhmageOMHSDK/RSRPSupport"
  pod "ResearchSuiteTaskBuilder"
  pod "ResearchSuiteResultsProcessor"

  # pod "OhmageOMHSDK", :path => '../../../../ohmage/RSuiteSDKs/OhmageOMHSDK'
  # pod "OhmageOMHSDK/RSTBSupport", :path => '../../../../ohmage/RSuiteSDKs/OhmageOMHSDK'
  # pod "OhmageOMHSDK/RSRPSupport",:path => '../../../../ohmage/RSuiteSDKs/OhmageOMHSDK'
  # pod "ResearchSuiteTaskBuilder",:path => '../../ResearchSuiteTaskBuilder-ios'
  # pod "sdlrkx", :path => '../../sdl-rkx'
  # pod "ResearchSuiteResultsProcessor", :path => '../../ResearchSuiteResultsProcessor'

  target 'ResearchSuiteAppFramework_Tests' do
    inherit! :search_paths


  end
end
